spring:
  profiles:
    active: dev
---
server:
  port: 8001
mybatis:
  type-aliases-package: com.czq.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
spring:
  profiles: dev
  application:
    name: springcloud-config-dept #服务名称必须一致
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloudtest2?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7004/eureka/,http://localhost:7003/eureka/
  instance:
    instance-id: springcloud-pro-8001
    prefer-ip-address: true #显示IP

#Eureka配置
info:
  app.name: pro-8001
  company.name: qiang.com

---
server:
  port: 8002
mybatis:
  type-aliases-package: com.czq.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
spring:
  profiles: test
  application:
    name: springcloud-config-dept #服务名称必须一致
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloudtest1?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7004/eureka/,http://localhost:7003/eureka/
  instance:
    instance-id: springcloud-pro-8002
    prefer-ip-address: true #显示IP

#Eureka配置
info:
  app.name: pro-8002
  company.name: qiang.com
