spring:
  profiles: 
    active: dev
---
server:
  port: 8201
spring:
  profiles: dev
  application:
    name: springcloud-pro-dept #服务名称必须一致
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
---
server:
  port: 8202
spring:
  profiles: test
  application:
    name: springcloud-pro-test

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
